#!/usr/bin/env bash

###############################################################################
# parse_test_folds.sh
#
# Purpose
# -------
# This script parses the test portion of each fold in a 10-fold cross-validation
# pipeline for dependency parsing using UDPipe.
#
# For each fold N (1..10), the script applies the trained model `model-N.output`
# to the corresponding test file `test-N.conllu`, producing a parsed output file
# `test-N.out.conllu`.
#
# Naming convention
# -----------------
#   model-N.output      UDPipe model trained on the training portion of fold N
#   test-N.conllu       Gold test data for fold N
#   test-N.out.conllu   Parsed output generated by this script
#
# Example command executed internally for fold 6:
#
#   udpipe --parse model-6.output test-6.conllu > test-6.out.conllu
#
# Requirements
# ------------
# - UDPipe must be installed and available in the system PATH.
# - The script must be executed in the directory containing the model and
#   test files.
#
# Usage
# -----
#   chmod +x parse_test_folds.sh
#   ./parse_test_folds.sh
#
# Output
# ------
# For each fold N, the script produces:
#
#   test-N.out.conllu
#
# which contains the dependency parses predicted by UDPipe.
#
###############################################################################

for N in {1..10}; do

    model="model-${N}.output"
    testfile="test-${N}.conllu"
    outfile="test-${N}.out.conllu"

    # Check that required files exist
    if [[ ! -f "$model" ]]; then
        echo "Skipping fold $N: missing model file $model"
        continue
    fi

    if [[ ! -f "$testfile" ]]; then
        echo "Skipping fold $N: missing test file $testfile"
        continue
    fi

    echo "Fold $N: parsing $testfile using $model"
    echo "Output → $outfile"

    udpipe --parse "$model" "$testfile" > "$outfile"

done

echo "Parsing completed for all folds."